config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount API => '/api'

  root 'welcome#index'

  resources :articles do
    get 'show_more', on: :member
    collection do
      get 'test_json'
      get 'test_js'
      get 'search'
    end
    resources :comments
  end

  resources :tags

  resources :users do
    collection do
      get 'signup'
      get 'login'
      post 'create_login_session'
      delete 'logout'
    end
    member do
      patch 'upload'
    end
  end

  get '/auth/:provider/callback' => 'oauth#create_login_session'
end

app/models/article.rb
class Article < ActiveRecord::Base
  include ArticleSearchable
  include Cacheable


  #self.table_name = "articles"
  #self.primary_key = "id"

  #单个设
  validates :title, presence: true
  validates :text, presence: true
  #批量设
  #validates_presence_of :title, :text

  validates :email, confirmation: true
  validates :email_confirmation, presence: true

  #自定义验证
  #validate :custom_valid

  #def custom_valid
  #  errors.add(:expiration_date, "can't be in the past")
  #  errors[:base] << "Expiration date can't be in the past" #错误消息可以添加到整个对象上，而不是针对某个属性。
  #end

  #不会存入数据库
  validates :terms_of_service, acceptance: true

  #对象生命周期内回调
  #log = ""
  #
  #after_initialize do
  #  puts "article --after initialize #{log}"
  #end
  #
  #before_validation do
  #  puts "article --before validation #{log}"
  #end
  #
  #after_validation do
  #  puts "article --before validation #{log}"
  #end
  #
  #before_save do
  #  puts "article --before save #{log}"
  #end
  #
  #before_create do
  #  puts "article --before create #{log}"
  #end
  #
  #after_create do
  #  puts "article --after create #{log}"
  #end
  #
  #before_update do
  #  puts "article --before update #{log}"
  #end
  #
  #after_update do
  #  puts "article --after update #{log}"
  #end
  #
  #after_save do
  #  puts "article --after save #{log}"
  #end
  #
  #before_destroy do
  #  puts "article --before destroy #{log}"
  #end
  #
  #after_destroy do
  #  puts "article --after destroy #{log}"
  #end
  #after_commit do
  #  puts "article --after commit #{log}"
  #end

  #删除文章时关联删除评论
  has_many :comments, dependent: :destroy


  #Article对象获得的隐式方法
  #@article.tags(force_reload = false)
  #@article.tags<<(object, ...)
  #@article.tags.delete(object, ...)
  #@article.tags.destroy(object, ...)
  #@article.tags=objects
  #@article.tag_ids
  #@article.tag_ids=ids
  #@article.tags.clear
  #@article.tags.empty?
  #@article.tags.size
  #@article.tags.find(...)
  #@article.tags.where(...)
  #@article.tags.exists?(...)
  #@article.tags.build(attributes = {}, ...)
  #@article.tags.create(attributes = {})
  #@article.tags.create!(attributes = {})
  has_many :articles_tags
  has_many :tags, through: :articles_tags


  #指定默认作用域
  default_scope { order(updated_at: :desc) }

  #可以在类上或者作为关联对象被调用
  scope :active, -> { where(state: 1) }
  scope :inactive, -> { where(state: 0) }

  #把article和它的comments一起保存
  accepts_nested_attributes_for :comments

  #写法一
  #after_commit Proc.new {|article| cache_write article}, on: [:create, :update]
  #after_commit Proc.new {|article| cache_delete article}, on: :destroy

  #写法二
  #after_commit lambda { |article| cache_write article}, on: [:create, :update]
  #after_commit lambda { |article| cache_delete article}, on: :destroy

  #写法三
  #after_commit -> { cache_write self}, on: [:create, :update]
  #after_commit -> { cache_delete self}, on: :destroy

  #写法四
  #after_commit :f1, on: [:create, :update]
  #after_commit :f2, on: :destroy
  #
  #def f1
  #  cache_write self
  #end
  #
  #def f2
  #  cache_delete self
  #end

  #写法五
  #自动实时索引
  after_commit on: [:create] do
    cache_write self
    __elasticsearch__.index_document
  end

  after_commit on: [:update] do
    cache_write self
    __elasticsearch__.update_document
  end

  after_commit on: [:destroy] do
    cache_delete self
    __elasticsearch__.delete_document
  end

  def self.db_search(query)
    if query.blank?
      all
    else
      where('title like :search or text like :search', search: "%#{query}%")
    end
  end

  def self.db_search_only(query, page, per_page)
    db_search(query).page(page).per(per_page)
  end

  def self.db_search_mixin_cache(query, page, per_page)
    articles = db_search(query).page(page).per(per_page)
    if articles.size > 0
      article_ids = articles.map{|a|"article_#{a.id}"}
      array_articles = cache_read_multi(article_ids)
    else
      array_articles = []
    end
    Kaminari.paginate_array(array_articles, {limit: articles.limit_value, offset: articles.offset_value, total_count: articles.total_count})
  end

  def self.es_search_only(query, page, per_page)
    search(query).page(page).per(per_page).records
  end

  def self.es_search_mixin_cache(query, page, per_page)
    response = search(query).page(page).per(per_page)
    if response.results.total > 0
      article_ids = response.results.map{|result|"article_#{result._source.id}"}
      #article_ids = response.results.map{|result| [Article.class.to_s.underscore, result._source.id].join('-')}
      array_articles = cache_read_multi(article_ids)
    else
      array_articles = []
    end
    Kaminari.paginate_array(array_articles, {limit: response.limit_value, offset: response.offset_value, total_count: response.total_count})
  end

end
#实例方法不能调类方法
#类方法不能调实例方法

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #before_action do
  #  @tags = Tag.all
  #end

  before_action :load_tags, only: [:new, :edit, :update, :create]

  before_action :load_article, only: [:show, :show_more, :edit, :update, :destroy]

  #around_action :take_how_long, only: :search


  def new
    #@tags = Tag.all
    @article = Article.new

    @article.comments.build
    #3.times { @article.comments.build }
  end

  def create
    #{"utf8"=>"✓", "authenticity_token"=>"dPKH+6wpwb60HHbpiF8eED765ZManGKqo5yGxtwOq+WDHPHEwYnVELuPE4TSyP2ND29RfPpwEtcQt3irVzftuw==", "my_article"=>{"title"=>"a", "text"=>"b"}, "commit"=>"提交", "controller"=>"articles", "action"=>"create"}
    #render plain: params.inspect

    #{"title"=>"a", "text"=>"b"}
    #render plain: params[:my_article].inspect

    #a
    #render plain: params[:my_article][:title]

    #@article = Article.new
    #@article.title = params[:my_article][:title]
    #@article.text = params[:my_article][:text]
    #@article.save

    @article = Article.new(article_params)
    if @article.save
      #redirect_to action: 'show', id: @article.id
      #redirect_to action: 'show', id: @article
      #redirect_to article_path(@article.id)
      redirect_to article_path(@article)
      #redirect_to @article
    else
      #byebug
      #render 'new'
      render new_article_path
    end

  end

  def show
    #@article = Article.find(params[:id])
    #@comments = @article.comments.order(created_at: :desc).page(params[:page])
    @comments = @article.comments.page(params[:page])
  end

  def show_more
    #render js: "alert('hello')"

    #@article = Article.find(params[:id])
    #@comments = @article.comments.order(created_at: :desc).page(params[:page])
    @comments = @article.comments.page(params[:page])
  end

  #https://github.com/amatsuda/kaminari/issues/293
  #https://github.com/amatsuda/kaminari
  # Paginating a generic Array object
  def index
    #@articles = Article.all.page(params[:pg]).per(3)
    #@articles = Article.all.page(params[:page]).includes(:comments)  #用includes避免n+1查询

    #查看sql执行计划: Article.all.page(params[:page]).explain
    @articles = Article.all.page(params[:page])
  end

  def edit
    #@tags = Tag.all
    #@article = Article.find(params[:id])
    unless current_user
      session[:return_to] = request.url
      redirect_to login_users_path
    end
  end

  def update
    #@tags = Tag.all
    #{"utf8"=>"✓", "_method"=>"patch", "authenticity_token"=>"lFMCKRUMGK//mlqDrYi7gYrcIqFz6wPWdNNvBfpwJs9zJV7HL4EwDgDrvp8oeKbFnR4JnSrsczGPIeWfHx1klA==",
    # "article"=>{"title"=>"a", "text"=>"b", "email"=>"qracle@126.com", "email_confirmation"=>"",
    # "terms_of_service"=>"0", "tag_ids"=>["1", "2", "3", "4"]}, "commit"=>"提交", "controller"=>"articles", "action"=>"update", "id"=>"9"}
    #render plain: params

    #@article = Article.find(params[:id])


    #单独赋值时不会使用strong parameter验证
    #@article.title = params[:article][:title]
    #@article.text = params[:article][:text]
    #@article.email = params[:article][:email]
    #@article.tag_ids = params[:article][:tag_ids]
    #@article.email_confirmation = params[:article][:email_confirmation]
    #if @article.save

    #if @article.update_attributes(article_params)
    if @article.update(article_params)
      #redirect_to @article
      redirect_to article_path(@article)
    else
      render 'edit'
      #render edit_article_path(@article)
    end
  end

  def destroy
    #@article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def test_json
    render json: Article.all.limit(3).to_json
  end

  def test_js
  end

  def search
    #@articles = Article.all.page(params[:page])
    #if params[:search].present?

      #条件查询
      #以下所有写法等效

      #1.纯字符串方式，有SQL注入问题，永远不要这么写
      #@articles = @articles.where("title = '#{params[:search]}' and text = '#{params[:search]}'")

      #2.数组方式
      #@articles = @articles.where('title = ? and text = ?', params[:search], params[:search])

      #3.占位符方式
      #@articles = @articles.where('title = :search and text = :search', search: params[:search])

      #4.Hash方式完整写
      #@articles = @articles.where(articles: { title: params[:search], text: params[:search] })

      #5.Hash方式简写
      #@articles = @articles.where(title: params[:search], text: params[:search])

      #6.把and条件分开写
      #@articles = @articles.where(title: params[:search]).where(text: params[:search])

      #or条件就不能用hash方式写了
      #完全匹配
      #@articles = @articles.where('title = :search or text = :search', search: params[:search])

      #模糊匹配
      #@articles = @articles.where('title like :search or text like :search', search: "%#{params[:search]}%")
    #end

    #性能比较
    #@articles = db_search_only(params[:search])
    #@articles = db_search_mixin_cache(params[:search])
    #@articles = es_search_only(params[:search])
    #@articles = es_search_mixin_cache(params[:search])

    #移动到model层
    #@articles = Article.db_search_only(params[:search], params[:page], params[:per_page])
    #@articles = Article.db_search_mixin_cache(params[:search], params[:page], params[:per_page])
    #@articles = Article.es_search_only(params[:search], params[:page], params[:per_page])
    @articles = Article.es_search_mixin_cache(params[:search], params[:page], params[:per_page])

    #render plain: @articles.to_json and return

    render 'index'
  end

  private
  def article_params
    #params.require(:article).permit!
    #params.require(:my_article).permit(:title, :text)
    params.require(:article).permit(:title, :text, :email, :email_confirmation, :terms_of_service, { tag_ids:[] }, :state,
                                    comments_attributes: [:id, :commenter, :body])
  end

  def load_article
    @article = Article.find(params[:id])
  end

  def load_tags
    @tags = Tag.all
  end

  #def db_search_only(query)
  #  Article.db_search(query).page(params[:page])
  #end
  #
  #def db_search_mixin_cache(query)
  #  articles = Article.db_search(query).page(params[:page])
  #    if articles.size > 0
  #      article_ids = articles.map{|a|"article_#{a.id}"}
  #      #array_articles = Rails.cache.read_multi(*article_ids).values
  #      array_articles = $redis.mget(*article_ids).map{|json_string| Article.new(JSON.parse(json_string))}
  #    else
  #      array_articles = []
  #    end
  #    Kaminari.paginate_array(array_articles, {limit: articles.limit_value, offset: articles.offset_value, total_count: articles.total_count})
  #end
  #
  #def es_search_only(query)
  #  Article.search(params[:search]).page(params[:page]).records
  #end
  #
  #def es_search_mixin_cache(query)
  #  response = Article.search(query).page(params[:page])
  #  if response.results.total > 0
  #    article_ids = response.results.map{|result|"article_#{result._source.id}"}
  #    #array_articles = Rails.cache.read_multi(*article_ids).values
  #    array_articles = $redis.mget(*article_ids).map{|json_string| Article.new(JSON.parse(json_string))}
  #  else
  #    array_articles = []
  #  end
  #  Kaminari.paginate_array(array_articles, {limit: response.limit_value, offset: response.offset_value, total_count: response.total_count})
  #end

  #def take_how_long
  #  begin_time = Time.zone.now.to_f
  #  yield
  #  end_time = Time.zone.now.to_f
  #  time = (end_time - begin_time) * 1000
  #  puts "耗时：#{time}毫秒"
  #end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  #实时缓存
  def cache_key_for_articles_list(articles, search)
    prefix = "articles/list"
    if articles.any?
      seq_no = articles.map(&:updated_at).max.to_s(:number)
    end
    if search.present?
      prefix = prefix + "/search"
    end
    "#{prefix}/#{seq_no}"
  end
end

app/views/articles/_comment.html.erb
<p>
  <strong><%= t('.commenter') %>:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong><%= t('.body') %>:</strong>
  <%= comment.body %>
</p>

<p>
  <strong><%= t('.created_at') %>:</strong>
  <%= l comment.created_at, format: :long %>
</p>

<%= link_to "Delete", article_comment_path(article, comment), { method: :delete, data: { confirm: 'Are you sure?' } } %>

app/views/articles/_comments.html.erb
<%# comments.each do |comment| %>
    <%#= render partial: 'articles/comment', locals: { comment: comment, article: article } %>
<%# end %>

<!-- render collection可以省略foreach遍历，这里有过度重构的嫌疑 -->
<%= render partial: 'articles/comment', collection: comments, locals: { article: article } %>

<%#= link_to_next_page comments, 'Show More', { remote: true, params: {controller: 'articles', action: 'show_more'}, id: 'show_more_link' } %>

<!-- 从CommentsController传过来的参数只有article_id，没有id值，所以这里需要把id赋值回来 -->
<%= link_to_next_page comments, 'Show More', { remote: true, params: {controller: 'articles', action: 'show_more', id: params[:id] || params[:article_id]}, id: 'show_more_link' } %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, {class: 'form_control'} %>
    </div>

    <div class="form-group">
      <%= f.label :text %>
      <%= f.text_area :text, {class: 'form_control', size: '60x12'} %>
    </div>


    <%= f.label :email %>
    <%= f.email_field :email %>
    <%#= f.text_field :email %>   <!-- 表单有对应的模型对象，key名固定为模型名 -->
    <%#= text_field :article, :email %> <!-- 亦是表单有对应的模型对象，可自定义key名 -->
    <%#= text_field_tag 'article[email]', @article.email %> <!-- 无模型对象表单 -->



    <%= f.label :email_confirmation %>
    <%= f.email_field :email_confirmation %>
    <%#= f.text_field :email_confirmation %>
    <%#= text_field :article, :email_confirmation %>
    <%#= text_field_tag 'article[email_confirmation]' %>

<!--
ouputs:
    <input type="checkbox" value="1" name="article[terms_of_service]" id="article_terms_of_service" />
-->
    <%= f.check_box :terms_of_service, {checked: true} %>
    <%#= check_box :article, :terms_of_service %>
    <%#= check_box_tag 'article[terms_of_service]' %>
<!--
Outputs:
<label for="article_terms_of_service">服务条款</label>
-->
    <%= f.label :terms_of_service, '服务条款' %>
    <%#= f.label :terms_of_service %>

    <!--def check_box_tag(name, value = "1", checked = false, options = {})-->
    <% @tags.each do |tag| %>
        <%= check_box_tag 'article[tag_ids][]', tag.id, @article.tags.include?(tag), {id: dom_id(tag)} %>
        <%= label_tag dom_id(tag), tag.name %>
    <% end %>

    <!--
    复选按钮可以直接转成单选按钮，只不过name数组里只存一个值而已
    -->
    <!--
    <%# @tags.each do |tag| %>
        <%#= radio_button_tag 'article[tag_ids][]', tag.id, @article.tags.include?(tag), {id: dom_id(tag)} %>
        <%#= label_tag dom_id(tag), tag.name %>
    <%# end %>
    -->


    <!--
    下拉框的多种写法，效果是一样的
    -->
    <%#= select_tag 'article[tag_ids][]', '<option value="1">计算机</option><option value="2" selected>英语</option>'.html_safe %>
    <%#= select_tag 'article[tag_ids][]', options_for_select([['计算机', 1], ['英语', 2]], 2) %>
    <%#= select_tag 'article[tag_ids][]', options_for_select({'计算机' => 1, '英语' => 2}, 2) %>
    <%#= select_tag 'article[tag_ids][]', options_for_select({计算机: 1, 英语: 2}, 2) %>
    <%#= select_tag 'article[tag_ids][]', options_for_select(@tags.map { |tag| [tag.name, tag.id] }, 2) %>
    <%#= select_tag 'article[tag_ids][]', options_from_collection_for_select(@tags, :id, :name, 2) %>

    <%= f.label :state %>
    <%= f.select :state, options_for_select([['active', 1], ['inactive', 0]], @article.state) %>

    <!--关联保存-->
    <%#= f.fields_for :comments, @article.comments do |ff| %>
    <%= f.fields_for :comments do |ff| %>
        <%= ff.label :commenter %>
        <%= ff.text_field :commenter %>

        <%= ff.label :body %>
        <%= ff.text_area :body %>
    <% end %>

    <%= f.submit '提交', class: 'btn btn-primary' %>
<% end %>


  <!--text_area_tag: <%= text_area_tag(:message, "Hi, nice site", size: "24x6") %><br>-->
  <!--password_field_tag: <%= password_field_tag(:password) %><br>-->
  <!--hidden_field_tag: <%= hidden_field_tag(:parent_id, "5") %><br>-->
  <!--search_field:<%= search_field(:user, :name) %><br>-->
  <!--telephone_field:<%= telephone_field(:user, :phone) %><br>-->
  <!--date_field:<%= date_field(:user, :born_on) %><br>-->
  <!--datetime_field:<%= datetime_field(:user, :meeting_time) %><br>-->
  <!--datetime_local_field:<%= datetime_local_field(:user, :graduation_day) %><br>-->
  <!--month_field:<%= month_field(:user, :birthday_month) %><br>-->
  <!--week_field:<%= week_field(:user, :birthday_week) %><br>-->
  <!--url_field:<%= url_field(:user, :homepage) %><br>-->
  <!--email_field:<%= email_field(:user, :address) %><br>-->
  <!--color_field:<%= color_field(:user, :favorite_color) %><br>-->
  <!--time_field:<%= time_field(:task, :started_at) %><br>-->
  <!--number_field:<%= number_field(:product, :price, in: 1.0..20.0, step: 0.5) %><br>-->
  <!--range_field:<%= range_field(:product, :discount, in: 1..100) %><br>-->

app/views/articles/edit.html.erb
<h1>Edit Article #<%= @article.id %></h1>

<!--
<form action="/articles/5" accept-charset="UTF-8" method="post">
    <input name="utf8" type="hidden" value="&#x2713;" />
    <input type="hidden" name="_method" value="patch" />
    <input type="hidden" name="authenticity_token" value="059/6RZ1qGWtFX2laxNp2lDLaamri/YppPDRuJNP3XQkcQnWe9W8y6KGGMgxhIpHYV7dRktnhlQX2y/VGHabKg==" />

    <label for="article_title">Title</label>
    <input type="text" value="a" name="article[title]" id="article_title" />

    <label for="article_text">Text</label>
    <textarea name="article[text]" id="article_text">
b</textarea>

    <input type="submit" name="commit" value="提交" />
</form>
-->

<!--
<%#= form_for :my_article, url: articles_path, method: :patch do |f| %>
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
<%#= form_for @article do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :text %>
    <%= f.text_area :text %>

    <%= f.submit('提交') %>
<% end %>
-->

<%= render 'form' %>

<!--
why framework adds <div class="field_with_errors"> for me when errors occur???
-->
<% if @article.errors.any? %>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%#= link_to 'Back', @article %>
<%= link_to 'Back', articles_path, class: 'btn btn-default' %>

app/views/articles/index.html.erb
<%= content_for :title do %>
    <title>Articles</title>
<% end %>

<h1>Listing articles</h1>

<%= link_to 'New', new_article_path %>

<!--因为没有model，所以使用普通表单-->
<%= form_tag search_articles_path, method: :get do %>
    <%= search_field_tag('search', params[:search], { placeholder: '在这里输入查询关键字' }) %>
    <%= submit_tag('搜索') %>
<% end %>

<%# cache ["articles/list", @articles.map(&:updated_at).max.to_s(:number)] do %>
<%# cache_if @articles.any?, ["articles/list", @articles.map(&:updated_at).max.try(:to_s, :number)] do %>
<%# cache_if @articles.any?, cache_key_for_articles_list(@articles, params[:search]) do %>
<div class="table-responsive">
  <table class="table table-striped table-condensed">
    <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Text</th>
      <th></th>
      <th colspan="10">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @articles.each do |article| %>
        <%# cache article do %><!--套娃缓存性能并不高，过多的io-->
        <tr>
          <td><%= article.id %></td>
          <td><%= article.title %></td>
          <td><%= article.text %></td>
          <!--必须用size不能用count，size才会判断has_cached_counter?-->
          <td><%#= article.comments.map(&:commenter) %><%= article.comments.size %></td><!-- 这个地方可能产生n+1查询 -->
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Show', article_path(article) %></td>
          <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
        <%# end %>
    <% end %>
    </tbody>
  </table>
</div>
<%# end %>

<!-- https://github.com/amatsuda/kaminari -->
<%#= paginate @articles, window: 2, :param_name => :pg %>
<%= paginate @articles %>

<%#= request.params %>
<%= link_to_previous_page @articles, 'Previous Page', params: params.merge!(request.params) %>
<%= link_to_next_page @articles, 'Next Page', params: params.merge!(request.params) %>

<%= page_entries_info @articles, entry_name: '' %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<!--
<form action="/articles" accept-charset="UTF-8" method="post">
  <input name="utf8" type="hidden" value="&#x2713;" />
  <input type="hidden" name="authenticity_token" value="7iuEmqhm3BGZN7HTh/VSLxrERJ1B33SIiWTTwYDsLlkZxfKlxcbIv5ak1L7dYrGyK1HwcqEzBPU6Ty2sC9VoBw==" />

  <label for="my_article_title">Title</label>
  <input type="text" name="my_article[title]" id="my_article_title" />

  <label for="my_article_text">Text</label>
  <textarea name="my_article[text]" id="my_article_text">
  </textarea>

  <input type="submit" name="commit" value="提交" />
</form>
-->

<!--
<%#= form_for :my_article, url: articles_path, method: :post do |f| %>
<%= form_for :article, url: articles_path, method: :post do |f| %>
<%#= form_for @article do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :text %>
    <%= f.text_area :text %>

    <%= f.submit('提交') %>
<% end %>
-->

<%= render 'form' %>

<!--
why framework adds <div class="field_with_errors"> for me when errors occur???
-->
<% if @article.errors.any? %>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%#= link_to 'Back', @article %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <!--<strong><%= t('show.title', scope: [:articles]) %>:</strong>-->
  <!--<strong><%= t(:title, scope: [:articles, :show]) %>:</strong>-->
  <!--<strong><%= t('articles.show.title') %>:</strong>-->
  <strong><%= t('.title') %>:</strong>
  <%= @article.title %>
</p>

<p>
  <strong><%= t('.text') %>:</strong>
  <%= @article.text %>
</p>


<h2>Comments</h2>
<div id="ajax_comments">
  <%= render partial: 'articles/comments', locals: { article: @article, comments: @comments } %>
</div>



<h2>Add a comment:</h2>
<%#= form_for([@article, @article.comments.build]) do |f| %>
<%#= form_for :comment, url: article_comments_path(@article), method: :post do |f| %>

<!-- 下两种写法才会自动绑定到model的翻译文件 -->
<%#= form_for Comment.new, url: article_comments_path(@article), method: :post do |f| %>

<%#= form_for [@article, @article.comments.build] do |f| %>
<!--把新增评论也变成Ajax的-->
<%= form_for [@article, @article.comments.build], remote: true do |f| %>
      <%= f.label :commenter %>
      <%= f.text_field :commenter %>

      <%= f.label :body %>
      <%= f.text_area :body %>

      <%= f.submit("提交")%>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>


<input type="button" id="json_btn" value="测试返回json" />
<input type="button" id="js_btn" value="测试返回js" />

<script>
  $(function(){
      $("#json_btn").click(function(){
          $.ajax({
              url: "<%= test_json_articles_path %>",
              type: "GET",
              data_type: "json",
              success: function(data){
                  alert(JSON.stringify(data));
              },
              error: function(){
                  alert("error");
              }
          });
      });
      $("#js_btn").click(function(){
          $.ajax({
              url: "<%= test_js_articles_path %>",
              type: "GET",
              data_type: "script"
              //无需下面这种方式的回调，rails已经在服务端处理掉了回调工作
//              ,success: function(data){
//                  alert("hello");
//              },
//              error: function(){
//                  alert("error");
//              }
          });
      });
  });
</script>

app/views/articles/show.js.erb
<!-- 由于该页面会被多个controller共享，所以路径要写全，否则只有自己的controller能找到，其他的controller都找不到它 -->
$("#ajax_comments").html("<%= j render(partial: 'articles/comments', locals: { article: @article, comments: @comments }) %>");

app/views/articles/show_more.js.erb
//alert('hello');
//alert("<%#= j render 'comments' %>");//不加escape_javascript不会输出js字符串
$("#show_more_link").remove();

<!-- 这里路径可以不写全，因为渲染show_more页面的是自己的controller -->
$("#ajax_comments").append("<%= j render(partial: 'comments', locals: { article: @article, comments: @comments }) %>");
//$("#ajax_comments").append("<%#= j render(partial: 'articles/comments', locals: { article: @article, comments: @comments }) %>");

app/views/articles/test_js.js.erb
alert("hi");