config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount API => '/api'

  root 'welcome#index'

  resources :articles do
    get 'show_more', on: :member
    collection do
      get 'test_json'
      get 'test_js'
      get 'search'
    end
    resources :comments
  end

  resources :tags

  resources :users do
    collection do
      get 'signup'
      get 'login'
      post 'create_login_session'
      delete 'logout'
    end
    member do
      patch 'upload'
    end
  end

  get '/auth/:provider/callback' => 'oauth#create_login_session'
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader

  #validates :name, presence: true
  #validates :email, presence: true
  #validates :avatar, presence: true, on: :update #创建用户的时候可以不传头像

  #会同时验证密码和确认密码，并加密密码
  #has_secure_password

  before_create :generate_token

  def generate_token
    begin
      self.auth_token = SecureRandom.urlsafe_base64
    end while User.exists?(auth_token: self.auth_token)
  end

  #user (id, ...)
  #picture (id, name, user_id, ...)
  has_one :picture, as: :imageable

  #保存user的时候要同时保存picture
  accepts_nested_attributes_for :picture
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    @picture = @user.picture || @user.build_picture
  end

  def update
    #最原始的上传图片到本地目录
    #uploaded_io = params[:user][:avatar]
    #File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    #  file.write(uploaded_io.read)
    #end

    # 使用carrierwave和上面等价的写法
    #uploader = AvatarUploader.new
    #uploader.store!(params[:user][:avatar])

    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def upload
    @user = User.find(params[:id])
    if @user.update_attribute(:avatar, params[:user][:avatar])
      respond_to do |format|
        format.html { redirect_to users_path }
        format.js { render 'upload' }
      end
    else
      render 'edit'
    end
  end

  def signup
    @user = User.new
  end

  def login
  end

  def create_login_session
    #render plain: params.inspect

    @user = User.find_by(name: params[:user][:name])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.auth_token
      redirect_to session[:return_to] || articles_path
    else
      render 'login'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #Active Job方式
      #同步发送邮件
      #UserMailer.welcome_email_smtp(@user.id).deliver_now
      #UserMailer.welcome_email_http(@user.id).deliver_now

      #异步发送邮件
      #https://github.com/mperham/sidekiq/wiki/Active-Job
      #UserMailer.welcome_email_smtp(@user.id).deliver_later
      UserMailer.welcome_email_http(@user.id).deliver_later

      #异步任务
      #ExampleJob.perform_later(@user.id)

      #异步任务里发送邮件
      #WelcomeEmailJobSMTP.perform_later(@user.id)
      #WelcomeEmailJobHTTP.perform_later(@user.id)
      #运行结果：
      #---------------------------------------------------------------------------------------- start ExampleJob
      #---------------------------------------------------------------------------------------- start WelcomeEmailJobSMTP
      #---------------------------------------------------------------------------------------- start WelcomeEmailJobHTTP
      #---------------------------------------------------------------------------------------- end WelcomeEmailJobHTTP
      #---------------------------------------------------------------------------------------- end WelcomeEmailJobSMTP
      #----------------------------------------------------------------------------------------fafds
      #---------------------------------------------------------------------------------------- end ExampleJob

      #纯sidekiq方式
      ExampleWorker.perform_async(@user.id)

      redirect_to articles_path
    else
      render 'signup'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to login_users_path
  end

  private
  def user_params
    #params.require(:user).permit!

    #picture_attributes的id是必须的
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :auth_token, picture_attributes: [ :id, :name, :imageable_id, :imageable_type ])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_image.html.erb
<%= image_tag(@user.avatar.small.url) %>

app/views/users/edit.html.erb
edit user<br>


------------------------------------------------------------ Show Avatar Pics ------------------------------------------------------------
<div>
  user.avatar.url: <%= @user.avatar.url %>
  <br>
  user.avatar.current_path: <%= @user.avatar.current_path %>
  <br>
  user.avatar_identifier: <%= @user.avatar_identifier %>
  <br>

  <% unless @user.avatar.nil? %>
      original:<%= image_tag(@user.avatar.url) %>
      small:<%= image_tag(@user.avatar.small.url) %>
      medium:<%= image_tag(@user.avatar.medium.url) %>
      large:<%= image_tag(@user.avatar.large.url) %>
  <% end %>
</div>

----------------------------------------------------------- Show Imageable Pics ----------------------------------------------------------
<div>
  <% unless @user.picture.nil? %>
      original:<%= image_tag(@user.picture.name.url) %>
      small:<%= image_tag(@user.picture.name.small.url) %>
      medium:<%= image_tag(@user.picture.name.medium.url) %>
      large:<%= image_tag(@user.picture.name.large.url) %>
  <% end %>
</div>


<%#= form_for @user, html: { multipart: true }  do |f| %>
<%#= f.file_field :avatar %>
<%#= f.text_field :name %>
<%#= f.text_field :email %>
<%#= f.submit %>
<%# end %>

<!-- 同时使用两种方式上传图片 -->
<%= form_for @user do |f| %>
    <%= f.fields_for :picture, @picture do |ff| %>
        <%= ff.label :name, 'Imageable' %><%= ff.file_field :name %>
        <%= ff.hidden_field :imageable_id %><!--可省略-->
        <%= ff.hidden_field :imageable_type %><!--可省略-->
    <% end %>
    <%= f.label :avatar %><%= f.file_field :avatar %>
    <%= f.label :name %><%= f.text_field :name %>
    <%= f.label :email %><%= f.text_field :email %>
    <%= f.submit %>
<% end %>

<% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>


----------------------------------------------------------- Ajax Fileupload ----------------------------------------------------------
<%= form_for @user, url: upload_user_path, remote: true do |f| %>
    <%= f.label :avatar %><%= f.file_field :avatar %>
    <%= f.submit 'Upload' %>
<% end %>

<div id="image_box">
  <%= render 'image' %>
</div>

app/views/users/index.html.erb
<%= content_for :title do %>
    <title>Users</title>
<% end %>

<h1>All Users</h1>

<table>
  <thead>
  <tr>
    <th>#</th>
    <th>name</th>
    <th>email</th>
    <th>Ops</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user) %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/users/login.html.erb
<%#= form_for('/users/create_login_session', method: :post, authenticity_token: true) do %>
<%#= form_tag({controller: 'users', action: 'create_login_session'}, method: :post, authenticity_token: true) do %>
<%#= form_tag('/users/create_login_session', method: :post, authenticity_token: true) do %>
<%= form_tag(create_login_session_users_path, method: :post, authenticity_token: true) do %>
    <%= label_tag :name, '用户名' %>
    <%= text_field_tag 'user[name]' %>

    <%= label_tag :password, '密码' %>
    <%= password_field_tag 'user[password]' %>

    <%= submit_tag '登录' %>
<% end %>

<%= link_to 'javascript:void(0)', id: 'qq_login' do %>
    <%= image_tag "Connect_logo_5.png" %>
<% end %>

<%= content_for :js do %>
<script>
    $(function(){
        $('#qq_login').click(function(){
            window.open("/auth/qq");
        });
    });
</script>
<% end %>

app/views/users/signup.html.erb
<%= form_for @user do |f| %>
    <%= f.label :name, "用户名" %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password, "密码" %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "请再输入一次" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "注册" %>
<% end %>


<% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

app/views/users/upload.js.erb
$("#image_box").append("<%= j render 'image' %>");