config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount API => '/api'

  root 'welcome#index'

  resources :articles do
    get 'show_more', on: :member
    collection do
      get 'test_json'
      get 'test_js'
      get 'search'
    end
    resources :comments
  end

  resources :tags

  resources :users do
    collection do
      get 'signup'
      get 'login'
      post 'create_login_session'
      delete 'logout'
    end
    member do
      patch 'upload'
    end
  end

  get '/auth/:provider/callback' => 'oauth#create_login_session'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :articles_tags
  has_many :articles, through: :articles_tags

  validates :name, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:alert] = '数据已经保存啦' #这种方式更灵活，可以自定义key名
      redirect_to new_tag_path#, alert: '数据已经保存啦'
    else
      flash.now[:alert] = '总之哪里出错啦' #render要用now，redirect_to不用加now
      render :new

      #各种等效写法
      #render 'new'
      #render 'new.html.erb'

      #render 'tags/new'
      #render 'tags/new.html.erb'

      #render action: 'new'
      #render action: :new

      #render template: 'tags/new'            #对
      #render template: 'tags/new.html.erb'   #对

      #render template: 'new'                 #错
      #render template: 'new.html.erb'        #错
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    tag = Tag.find(params[:id])
    tag.update(tag_params)
    redirect_to tags_path
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to tags_path
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= flash[:alert] if flash[:alert] %>

<%= form_for @tag do |f| %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

<% if @tag.errors.any? %>
    <ul>
      <% @tag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

app/views/tags/edit.html.erb
edit tag
<%= render 'form' %>

app/views/tags/index.html.erb
<%= content_for :title do %>
    <title>Tags</title>
<% end %>

<h1>All Tags</h1>

<table>
  <thead>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Ops</th>
  </tr>
  </thead>
  <tbody>
  <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.id %></td>
        <!--必须用size不能用count，size才会判断has_cached_counter?-->
        <td><%= tag.name %>(<%= tag.articles.size %>)</td>
        <td>
          <%= link_to 'Edit', edit_tag_path(tag) %>
          <%= link_to 'Delete', tag_path(tag), method: :delete %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New', new_tag_path %>

app/views/tags/new.html.erb
new tag
<%= render 'form' %>