config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount API => '/api'

  root 'welcome#index'

  resources :articles do
    get 'show_more', on: :member
    collection do
      get 'test_json'
      get 'test_js'
      get 'search'
    end
    resources :comments
  end

  resources :tags

  resources :users do
    collection do
      get 'signup'
      get 'login'
      post 'create_login_session'
      delete 'logout'
    end
    member do
      patch 'upload'
    end
  end

  get '/auth/:provider/callback' => 'oauth#create_login_session'
end

app/views/layouts/_footer.html.erb
<h1>Here is footer area</h1>

app/views/layouts/_header.html.erb
<h1>Here is header area</h1>

<% if current_user %>
    <%= link_to current_user.name, '#' %>
    <%= link_to current_user.auth_token, '#' %>
    <%= link_to 'logout', logout_users_path, method: :delete %>
<% else %>
    <%= link_to "signup", signup_users_path %>
    <%= link_to "login", login_users_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :title %><!--标题, 运行时会替换成每个页面各自的content_for :title块里的内容-->
  <%= yield :meta %><!--SEO-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--页头开始-->
<%= render 'layouts/header' %>
<!--页头结束-->
<!--正文开始-->
<%= yield %>
<!--正文结束-->
<!--页脚开始-->
<%= render 'layouts/footer' %>
<!--页脚结束-->
<!--js开始-->
<%= yield :js %>
<!--js结束-->
</body>
</html>